name: Subdub



on: 
 push:
    branches: [ main ]

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
   - name: checkoout
     uses: actions/checkout@v5

   - name: setup nodejs
     uses: actions/setup-node@v5
     with:
        node-version: '16' 
   - name: install dependencies
     run: npm install
   - name: run tests
     run: npm test    

